### ISSUE TITLE
전반적인 개발 환경을 설정합니다.

### ISSUE THREAD

**Issue by yu-heejin** [flow-team-project/flow-server#1]
## Description 📝
* Spring Boot 개발을 위한 전반적인 개발 환경을 설정합니다.

## TODO ✅
- [x] JPA, QueryDsl 등 전반적인 의존성 설정
- [x] 멀티모듈 구조 설정
- [x] Docker, docker-compose 추가
- [x] 브랜치 룰 추가
- [x] 이슈 템플릿 추가
- [x] PR 템플릿 추가
- [x] 실행 스크립트 추가
- [x] logback 추가
- [x] common response 추가
- [x] exceptionHandler 추가
